# Generated by Django 4.2.3 on 2023-07-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('ContactID', models.AutoField(primary_key=True, serialize=False)),
                ('ContactName', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('User', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
            ],
        ),
    ]
